# Generated by Django 2.0.5 on 2018-05-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppmb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftar',
            fields=[
                ('nik', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('asal_sekolah', models.CharField(max_length=50)),
                ('jenis_kelamin', models.CharField(max_length=1)),
                ('agama', models.CharField(max_length=15)),
                ('no_seluler', models.CharField(max_length=15)),
                ('tlp_rumah', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('jenjang', models.CharField(max_length=10)),
                ('akreditasi', models.CharField(max_length=2)),
                ('fakultas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppmb.Fakultas')),
            ],
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='pilihan1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan1', to='ppmb.Prodi'),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='pilihan2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan2', to='ppmb.Prodi'),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='pilihan3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan3', to='ppmb.Prodi'),
        ),
    ]
